name: emvqrjson
description: read or write emvqrcode
version: 1.1.0
homepage: https://github.com/chittaphonevansyli/emvqrcodejson.git

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  crclib: ^3.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
